[package]
name = "bytebit/reverse-array"
description = "A simple function that just reverses any array given to it."
version = "1.0.2"
license = "MIT"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
